import React from "react";
import { Pagediv,Page80div } from "../Assets/Css/cssPage2";
import Pagecard from "./PageCard";
import Image1 from "../Assets/Images/2.png";
import Image2 from "../Assets/Images/1.png";
import Image3 from "../Assets/Images/3.png";


const Page2 = () => {
  return (
    <Pagediv>
      <Page80div>
        <Pagecard
          image={Image1}
          tit={"Search"}
          des={
            "Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen."
          }
        />
        <Pagecard
          image={Image2}
          tit={"Select"}
          des={
            "Choose from thousands of options generated by the slogan maker that fit your needs."
          }
        />
        <Pagecard
          image={Image3}
          tit={"Stand out"}
          des={"Congrats on your new slogan. It's time to win the world!"}
        />
      </Page80div>
    </Pagediv>
  );
};

export default Page2;
